name: TestSite3
favicon: null
layout_spectrum: 0.5032943242695183
typography_spectrum: 0.29640674497932196
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.26611422724090517
  lightness: 0.10400578891858459
  saturation: 0.26364692905917764
  rhythmicContrast: 0.48228507372550666
purpose: []
